- name: advanced loop
  hosts: localhost
  become: yes
  tasks:
    - name: advanced loops
      ansible.builtin.yum:
        name: {{item.name}}
        state: {{item.state}}
      loop:
        - { name: 'nginx', state: 'present'}
        - { name: 'postfix', state: 'present'}
        - { name: 'maven', state: 'present'}  