- name: advanced loop
  hosts: localhost
  become: yes
  tasks:
    - name: advanced loops
      ansible.builtin.yum:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - { name: 'nginx', state: 'absent'}
        - { name: 'postfix', state: 'absent'}
        - { name: 'maven', state: 'absent'}  