- name: checking directory exists or not
  hosts: localhost
  become: yes
  tasks:
    - name: checking directory exists or not
      ansible.builtin.stat: 
        path: /home/ec2-user/app
      register: output
    - name: printing output
      ansible.builtin.debug:
        msg: "{{output}}"    
    - name: creating directory
      ansible.builtin.file:
        path: /home/ec2-user/app
        state: directory
      #when: output.stat.exists == false      