- name: variables precedence
  hosts: mongodb
  vars:
    name1: rakesh_from_play_level
  vars_files:
     variables.yaml
  vars_prompt:
  - name: name1
    prompt: what is your name?
    private: false 

        
  tasks:
  - name: variables precedence
    ansible.builtin.debug:
    vars:
      name1: rakesh_from_task
      msg: "my name is {{name1}}" 

