- name: variables precedence
  hosts: mongodb
  vars:
    name1: rakesh_from_play_level
  # vars_files:
  #   variables.yaml
  # vars_prompt:
  #   - name: name1
  #     prompt: what is your name?
  #     private: false

        
  tasks:
  - name: variables precedence
    #vars:
     # name1: rakesh_from_task
    ansible.builtin.debug:
      msg: "my name is {{name1}}" 

#1.command line
#2. task
#3. files
#4. prompt
